### ISSUE TITLE
Change redirect for MapLibre.org to MapLibre project

### ISSUE THREAD

**Issue by roblabs** [maplibre/maplibre.github.io#1]
The repos for MapLibre GL Native (native source & distribution) are now under the MapLibre project.  

Request to update the `window.location.href` to  `https://github.com/MapLibre` so that MapLibre.org redirectors to the project, not a specific repo within the project.  Or, if there is an existing plan to update this when the website is refreshed, then that's fine as well.

_E.G.,_ Update in the file:

https://github.com/maplibre/maplibre.github.io/blob/d2539f4f589e470fddd60854165e67413252d49c/index.html#L7

**Comment by lseelenbinder** [comment]
Fine with me. Do you mind opening a PR?

**Comment by lseelenbinder** [comment]
Thanks @roblabs! Merged.
