### ISSUE TITLE
Meeting notes

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre.github.io#10]
@klokan please let me know if you publish the meeting notes from yesterday, such that I can update the news section of maplibre.org with the relevant link. Thanks.

**Comment by klokan** [comment]
Thanks @wipfli & @nyurik - you were faster than me 🥇 
https://github.com/maplibre/maplibre/discussions/categories/steering-committee-meetings

**Comment by HarelM** [comment]
Can this be closed? Was this fixed by #11?
