### ISSUE TITLE
Inaccessible zoom buttons on the community map

### ISSUE THREAD

**Issue by zstadler** [maplibre/maplibre.github.io#115]
The zoom buttons of the [community map](https://maplibre.org/community) are inaccessible. They are hidden by the top ribbon

![image](https://user-images.githubusercontent.com/1304610/214007812-8db6743f-0b47-471f-a4af-75c21fca8a8c.png)

**Comment by maxammann** [comment]
I'd propose to just remove those. Alternatively we can move them to the bottom right/left.

**Comment by wipfli** [comment]
Good idea to move them down. @zstadler do you mind opening a pull request for moving the zoom controls down to a bottom cornor?

**Comment by zstadler** [comment]
@wipfli Unfortunately, I'm not qualified for this task.
