### ISSUE TITLE
Products page refers to Maptiler as documentation but this is another company

### ISSUE THREAD

**Issue by SjoerdPerfors** [maplibre/maplibre.github.io#13]
Make it more clear to the user that MapTiler can be used as an example how to integrate MapLibre products and repo's.

**Comment by SjoerdPerfors** [comment]
Proposal: https://github.com/maplibre/maplibre.github.io/pull/14

**Comment by nyurik** [comment]
The https://github.com/maplibre/maplibre.github.io/pull/14 was merged, should this be closed?
