### ISSUE TITLE
Highlights for newsletter

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre.github.io#139]
I want to write the March newsletter. What were the highlights since the last newsletter https://maplibre.org/news/2023-02-16-maplibre-newsletter-february-2023/ in MapLibre GL JS and MapLibre GL Native?

I will go through the commit history but would be great if you could give me some pointers @HarelM @louwers @ovivoda

**Comment by louwers** [comment]
Merged PRs: https://github.com/maplibre/maplibre-gl-native/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Amerged

Most notable PRs:

- New supported platform: Windows.
- TypeScript types for Node.js binding.
- Freed Android SDK from propietary dependencies making it possible to use MapLibre with Android applications submitted to F-Droid (10.0.0 release for Android).
- Render tests running on CI

Open discussions:

- Code organisation proposal https://github.com/maplibre/maplibre-gl-native/pull/789

People interested in contributing can schedule a call with me:

https://github.com/maplibre/maplibre-gl-native/discussions/898

Maybe link to the step-by-step guide for doing bounties: https://maplibre.org/roadmap/step-by-step-bounties-guide/
