### ISSUE TITLE
Update the status of the Metal project on the web page

### ISSUE THREAD

**Issue by ovivoda** [maplibre/maplibre.github.io#170]
Update the status in the Metal roadmap https://maplibre.org/roadmap/metal/

**Comment by ovivoda** [comment]
Opened up https://github.com/maplibre/maplibre.github.io/pull/172

**Comment by wipfli** [comment]
I would reference Issue and pull request the other way round. Because if you write in the pull request "closes #170", then once the pull request is merged, this issue gets closed automatically...
