### ISSUE TITLE
Community map icon ordering

### ISSUE THREAD

**Issue by nyurik** [maplibre/maplibre.github.io#185]
What is the ordering of the faces on the community map?  Do we sort them per commit count, per line count, or some other way?

**Comment by birkskyum** [comment]
If at all it's most likely to be alphabetic by name

**Comment by birkskyum** [comment]
No ordering from what I can tell

https://github.com/maplibre/maplibre.github.io/blob/main/data/community.json

**Comment by birkskyum** [comment]
https://github.com/maplibre/maplibre.github.io/blob/main/layouts/shortcodes/community-json.html

**Comment by maxammann** [comment]
We can easily randomize the z order :)
