### ISSUE TITLE
Reduce menu entries & Restructure

### ISSUE THREAD

**Issue by maxammann** [maplibre/maplibre.github.io#189]
I think the menu is quite messy right now. It is very hard to "parse" the menu in one go.

I would propose the following menu:

- Projects (Rename to "Docs & Roadmap"; most important to visitors as it contains links to documentation)
- News (Possibly rename to "Blog")
- About
- Jobs
- Donate
- ~~Roadmap~~ (Merge into Projects)
- ~Community~ (Merge into About)
- ~Sponsors~ (Merge into About)

5 is the absolute maximum. We can also think about remove "Donate" and somehow else advertise it. Jobs could be moved to the footer, and we could think about other ways to properly advertise it.

I think those two items are there right now because we want to "advertise" them, even though they are not that relevant for most people visiting.

**Comment by maxammann** [comment]
There are endless options to do this, but I think we should target 4 elements in the menu :)

**Comment by HarelM** [comment]
Maybe sponsors should be part of the donate? Feels that they are similar to me at least - i.e. have the sponsors in that page and a button to move to the current link.
In most cases I think jobs won't be appealing/interesting, I would consider adding that only when there are jobs opening or maybe do it as part of the about, IDK...
Not sure I would merge the community as part of the about, as it is one of the strategic pillars, so it might deserve a "page" of its own.
Just my thoughts, I agree that 5 would probably be a good maximum number.

**Comment by maxammann** [comment]
> Not sure I would merge the community as part of the about, as it is one of the strategic pillars, so it might deserve a "page" of its own.

I agree, though I guess it could have enough visibility on the About page. Especially because we are already presenting the team in About.

> In most cases I think jobs won't be appealing/interesting, I would consider adding that only when there are jobs opening or maybe do it as part of the about, IDK...

👍🏼

> Maybe sponsors should be part of the donate? Feels that they are similar to me at least - i.e. have the sponsors in that page and a button to move to the current link.

👍🏼

**Comment by louwers** [comment]
I would keep **Sponsors** for sure, since they are (and will probably continue to be) the most important source of income for the project. And they also pay in part for the publicity. It is also very important for our 'sales funnel' that this information is as easy to find as possible for interested party.

'About' is pretty generic, and if you click on it you see the faces of the MapLibre board and team, which is not in the first place what MapLibre is about. ;-) So my vote would be to merge Community into About, but keep the other pages as they are.

**Comment by birkskyum** [comment]
I believe one item we can remove is the donate link, which already exist under the sponsors page.

**Comment by birkskyum** [comment]
Another thing we can do is to move this top part of the jobs section to the about page:


The MapLibre Organization is an umbrella for open-source mapping libraries with the two central rendering projects being [MapLibre GL JS](https://github.com/maplibre/maplibre-gl-js) and [MapLibre Native](https://github.com/maplibre/maplibre-native) which are surrounded by an ecosystem of plugins and tools to generate maps. The MapLibre [Governing Board](https://maplibre.org/about/) was elected by the [Voting Members](https://github.com/maplibre/maplibre/blob/main/VOTING_MEMBERS.md), a group who represents the broader community, in August 2022 and is in charge to steer the Organization. The project coordinator is [Oliver Wipfli](https://github.com/wipfli) who supports the Governing Board in organizational tasks.

**Comment by birkskyum** [comment]
Things have changed quite a lot since the ticket was made, so I think it's reasonable to make a new ticket if there is more to be done.
