### ISSUE TITLE
Consider disabling the rotation on the front page

### ISSUE THREAD

**Issue by lnicola** [maplibre/maplibre.github.io#19]
It's fine if you want to keep it, but I opened https://maplibre.org/ for the first time today and when the rotation started it immediately made me nauseous. As far as I know, I don't have motion sickness, but this animation is too much for me. The zoom is fine, though.

As two more data points, @nyurik and a friend agreed with this.

**Comment by maxammann** [comment]
I created a PR, lets discuss this a final time :D
