### ISSUE TITLE
Enable branch protection for maplibre.github.io

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre.github.io#201]
Right now it is possible to accidentally push to main.

**Comment by birkskyum** [comment]
Just checked. Branch protection on the main branch appear to be enabled. I don't know when it was changed.

<img width="875" alt="Screenshot 2023-07-09 at 19 25 55" src="https://github.com/maplibre/maplibre.github.io/assets/74932975/e4b38a6d-3fbd-4c72-894d-fb6432c9801a">

**Comment by louwers** [comment]
@birkskyum There is a separate option that allows branch protection to be bypassed by admins.

**Comment by birkskyum** [comment]
Right, I updated that just now.
<img width="856" alt="Screenshot 2023-07-09 at 23 09 32" src="https://github.com/maplibre/maplibre.github.io/assets/74932975/522e63e6-909d-48a2-bb2e-adeb5f87fcbb">

**Comment by louwers** [comment]
Great. That helps with accidental pushed to main. :)
