### ISSUE TITLE
Fix space after links

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre.github.io#207]
Every link contains a space after it.

![image](https://github.com/maplibre/maplibre.github.io/assets/649392/c561561e-214b-4e72-aa9e-6f731423e104)

@maxammann Do you know if we can swap out / configure the Markdown compiler to fix this?

**Comment by maxammann** [comment]
I think it is due my custom link renderer here: https://github.com/maplibre/maplibre.github.io/blob/main/layouts/_default/_markup/render-link.html

It is probably the newline.

I'll take a look at home, currently on mobile.
