### ISSUE TITLE
Mention supported platforms for Native

### ISSUE THREAD

**Issue by ntadej** [maplibre/maplibre.github.io#252]
I think it would be good to mention supported platforms for Native on the homepage as it may help search discoverability. Now its very Android & iOS focused but Node and Qt are note mentioned.

/cc @birkskyum

**Comment by birkskyum** [comment]
I fully agree, and part of the intention with the ongoing restructure of having a project overview on the [landing page](https://maplibre.org/), is to allow for more in-depth project pages with a lot more details.

For Native I imagine that will include more information about Navigation, and SDK's like Flutter, React Native, Qt etc.

**Comment by ntadej** [comment]
I would still put some more keywords also on the landing page maybe (and then the details on the project-specific pages).

**Comment by birkskyum** [comment]
The current text says:

> Open-souce C++ library for displaying maps inside of your mobile
              applications, desktop application, or embedded devices.
              GPU-acceleration through OpenGL and Metal.
              
What do you suggest?
