### ISSUE TITLE
Broken link in https://maplibre.org/projects/#js

### ISSUE THREAD

**Issue by jimmyangel** [maplibre/maplibre.github.io#33]
The link to https://maplibre.org/maplibre-gl-js-docs is failing.

Chrome: This page isn’t working maplibre.org redirected you too many times.

Firefox: The page isn’t redirecting properly. An error occurred during a connection to maplibre.org.

Safari: Safari can't open the page. Too many redirects occurred...

**Comment by wipfli** [comment]
Thanks. https://github.com/maplibre/maplibre.github.io/pull/32

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre-gl-js-docs/issues/160
