### ISSUE TITLE
WARN  deprecated: data.GetJSON was deprecated in Hugo v0.123.0 and will be removed in a future release

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre.github.io#335]
Getting this warning:

> WARN  deprecated: data.GetJSON was deprecated in Hugo v0.123.0 and will be removed in a future release. use resources.Get or resources.GetRemote with transform.Unmarshal.

**Comment by CommanderStorm** [comment]
So sorry, should have looked if there is an issue to link.
This is resolved in https://github.com/maplibre/maplibre.github.io/pull/354

**Comment by louwers** [comment]
Thank you for fixing it!
