### ISSUE TITLE
"Leightweight" Renderer's

### ISSUE THREAD

**Issue by mynameisgump** [maplibre/maplibre.github.io#345]
Hello, just wondering if "leightweight" render's is a typo on the site or if I just don't know/understand the reference. If it is one I could do a short PR to fix it. Thanks!
<img width="451" alt="Screenshot 2024-10-21 at 12 38 34 PM" src="https://github.com/user-attachments/assets/cf71f2a4-c88c-4ca2-a24c-903ac91ef0a1">

**Comment by HarelM** [comment]
Closed by #346
