### ISSUE TITLE
Heading in overview

### ISSUE THREAD

**Issue by louwers** [maplibre/maplibre.github.io#358]
We updated Hugo, which fixed one issue, but I noticed that headings have started to show up on https://maplibre.org/news/

**Comment by louwers** [comment]
Sounds good and thank you!


What do you mean with the images don't work? For me the images load fine?

**Comment by CommanderStorm** [comment]
I mean the news entries with images

![Image](https://github.com/user-attachments/assets/0258ae15-00b9-40f3-bf57-5659e65cd941)

**Comment by louwers** [comment]
Oh I see, yes. The preview should just be the first paragraph I guess.
