### ISSUE TITLE
Map Libre icon image sample 404s

### ISSUE THREAD

**Issue by CuAnnan** [maplibre/maplibre.github.io#47]
I'm trying to figure out how to use custom markers in clustered layers but the given example doesn't actually load.

**Comment by CuAnnan** [comment]
https://maplibre.org/help/troubleshooting/using-recolorable-images-in-mapbox-maps/#mapbox-gl-js
404s

**Comment by wipfli** [comment]
Hi @CuAnnan where did you find that link?

**Comment by CuAnnan** [comment]
https://maplibre.org/maplibre-gl-js-docs/style-spec/layers/#symbol

**Comment by HarelM** [comment]
Seems like this is not the only broken link in the docs :-/
The link under `fill` is also broken and maybe others...
Are these links in the code comments or somewhere else?
