### ISSUE TITLE
Improve documentation page of MapLibre Native

### ISSUE THREAD

**Issue by manuelroth** [maplibre/maplibre.github.io#72]
Hi @birkskyum
As I understand, you are one of the maintainers of MapLibre Native. I really appreciate the work you are all doing on MapLibre. Thank you for your effort. I am currently evaluation MapLibre to be used for an upcoming project.

## Problem
At the moment the documentation of MapLibre Native only has links to the API-Documentation. It's really hard to get started without examples and guides. I am sure you are planning to expand the documentation in the future. It took me a long time to find the documentation by Mapbox for the "legacy" Mapbox Maps SDK. As Maplibre Native is just a fork of the "legacy" Mapbox Maps SDK all those examples and guides can be used with MapLibre.

<img width="724" alt="Screenshot 2022-09-02 at 17 07 24" src="https://user-images.githubusercontent.com/1810384/188179593-db1f9d99-ab3a-4241-a46d-e83aa340da27.png">

## Possible solution
Lets add a link on the [MapLibre Native](https://maplibre.org/projects/maplibre-native/) page which points to the examples on the "legacy" Mapbox Maps SDK ([iOS](https://docs.mapbox.com/ios/legacy/maps/guides/), [Android](https://docs.mapbox.com/android/legacy/maps/guides/)). This change would make it much easier for developers to get started with MapLibre Native. Once you found the time to copy over all those examples and guides to maplibre.org. We can just change the link.

<img width="683" alt="Screenshot 2022-09-02 at 17 09 39" src="https://user-images.githubusercontent.com/1810384/188179616-22e84a2d-7b4d-43ce-80ea-04163b6b3ade.png">

What do you think about this proposal?

**Comment by birkskyum** [comment]
Hi @manuelroth , thank you for taking the time to share this.

I know that there were also some other links previously to external examples - these I believe:

https://docs.maptiler.com/maplibre-gl-native-ios/
https://docs.maptiler.com/maplibre-gl-native-android/

Until we have official examples, I think it's a good idea to at least have links to "unofficial" ones as you suggest.
