### ISSUE TITLE
Point the main buttons on the main screen to the documentation pages and not to github

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre.github.io#9]
I think the Javascript button (and maybe the iOs/Android) should redirect the user to the documentation pages of the relevant platform and not the github repository.
The documentation should have a link to the github if anyone is interested is seeing the code etc, but I feel that most users will need to see the docs before the look at the repo...
What do you think?
![image](https://user-images.githubusercontent.com/3269297/141306271-61de190a-5553-483d-90ef-f6b3ef24abd8.png)
The site looks great BTW :-)

**Comment by wipfli** [comment]
Sounds good to me.

**Comment by klokan** [comment]
Originally, it should have been a link to the relevant section of the "Projects" under - https://maplibre.org/projects/.

If we add there id="js" - and an image to the right side - it would be perhaps the best landing place...

People could read about what is the project about - and then continue to GitHub, Examples or other documentation - and they could just scroll and see more of the projects.

PR welcome :-)
