### ISSUE TITLE
Better titles for browser tab

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre.github.io#94]
I'm not very familiar with hugo so I'm not sure I'll be able to help here, but I would like the title of the page (shown in the browser tab) to change when selecting different pages in the site.
For example when clicking "sponsors" I would like the chrome tab header to say MapLibre -Sponsors instead of Maplibre - MapLibre.
@maxammann is this possible and simple?
The following should say Maplibre - Home
![image](https://user-images.githubusercontent.com/3269297/203804588-1c4d52fd-57df-4e77-a981-54b32ae6be9b.png)
The following should say MapLibre - Community
![image](https://user-images.githubusercontent.com/3269297/203804694-aee269d6-13a7-481b-9a0d-41df63994433.png)
You get the point...

**Comment by maxammann** [comment]
Yeah I can fix that when I have time. Definitely possible

**Comment by HarelM** [comment]
I can probably send a PR if you direct me to the right location

**Comment by maxammann** [comment]
For some reason the .Title here refers to the sites title instead of the page's title:

https://github.com/maplibre/maplibre.github.io/blob/main/layouts/partials/head.html#L40

That could be because no page titles are set maybe.

**Comment by HarelM** [comment]
Is it paddocks that it's related to lower case vs upper case? I see that the title is defined in lowercase but the template has this in upper case. Not sure how relevant my observations are though.
